[package]
name = "samnefni"
description = "'samnefni' means 'alias' in icelandic."
version = "0.1.0"
authors = ["Olivier Detour <detour.olivier@gmail.com>"]

[dependencies]
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
